backend:
  name: git-gateway
  repo: Dimavi2804/MYM
  branch: main

media_folder: "img/productos"
public_folder: "img/productos"

collections:
  - name: "configuracion"
    label: "Catálogo de Ropa"
    delete: false
    editor:
      preview: false
    files:
      - name: "lista_productos"
        label: "Mis Prendas"
        file: "datos/productos.json"
        fields:
          - name: "productos"
            label: "Lista de Productos"
            widget: "list"
            fields:
              - { label: "ID Único", name: "id", widget: "datetime", format: "YYYYMMDDHHmmss", json_format: "YYYYMMDDHHmmss", default: "", required: true }
              - { label: "Nombre de la Prenda", name: "nombre", widget: "string" }
              - { label: "Precio ($)", name: "precio", widget: "number", value_type: "int" }
              - { label: "Categoría", name: "categoria", widget: "select", options: ["camperas", "pantalones", "remeras", "buzos", "polleras", "calzado", "otros"] }
              - { label: "Estado", name: "estado", widget: "select", options: ["nuevo", "usado"] }
              - { label: "Talle", name: "talle", widget: "string" }
              - { label: "Marca", name: "marca", widget: "string" }
              - { label: "Color", name: "color", widget: "string" }
              - { label: "Medidas", name: "medidas", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Imagen de Portada (Card)", name: "imagenCard", widget: "image" }
              - { label: "Imágenes de Detalle", name: "imagenesDetalle", widget: "list", field: { label: "Foto", name: "url", widget: "image" } }
              - { label: "Producto Activo en Web", name: "activo", widget: "boolean", default: true }
              - { label: "Vendido / Agotado", name: "vendido", widget: "boolean", default: false }